### ISSUE TITLE
Hate to be a complete newb

### ISSUE THREAD

**Issue by d1b1** [ParsePlatform/CloudCodeWebhooks-Express#2]
Can you provide a real world use case? I am new to parse and think I need to use this feature, but would love to understand how its expected to be used. I have seen references to web hooks for mailgun.

Does this code go in the main.js? 
Can it be called on the parse app domain without authentication?

**Comment by gfosco** [comment]
We're going to put together a better example soon.  This is for advanced users of cloud code who wish to use their own server, or a different programming language, for running cloud code.  We would just call you at your webhook URL rather than running code on Parse.  So it doesn't go in main.js (parse cloud code) and it isn't hosted by parse domains.  Sounds like you just want regular cloud code and not webhooks.

**Comment by d1b1** [comment]
thanks
